$('a[download]').css('border','1px solid red');// Простой атрибут
$('a[href="http://ya.ru"]').css('border', '1px solid red');//Полное сщщеветсвие
$('a[href!="http://ya.ru"]').css('border', '1px solid red');//Полное  не сщщеветсвие
$('a[href^="http"]').css('border', '1px solid red');//Начмнается с.....
$('a[href$=".com"]').css('border', '1px solid red');//Заканчивается на ....
$('a[href*="google"]').css('border', '1px solid red');//Содержит ....
$('a[data-tsrget|="main"]').css('border', '1px solid red');//Имеет префикс ...
$('a[href][download]').css('border', '1px solid red');//Имеед одновременно несколько атрибутов
